# Generated by Django 4.1 on 2022-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.TextField()),
                ('umur', models.BigIntegerField()),
                ('tinggi', models.BigIntegerField()),
                ('berat', models.BigIntegerField()),
                ('date_created', models.DateField()),
            ],
        ),
    ]
