# Generated by Django 4.1 on 2022-10-31 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_dokter', '0004_alter_modelinfodokter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokter', models.TextField(default='')),
                ('hari_praktek', models.TextField(default='')),
                ('jadwal_praktek', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelInfoDokter',
        ),
    ]
