# Generated by Django 4.1 on 2022-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_dokter', '0005_infodokter_reviewdokter_delete_modelinfodokter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodokter',
            name='jadwal_praktek',
            field=models.TextField(default=''),
        ),
    ]
