# Generated by Django 4.1 on 2022-11-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_dokter', '0006_alter_infodokter_jadwal_praktek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewDokter',
        ),
    ]
