# Generated by Django 4.1 on 2022-11-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan_akun', '0002_profile_allergies_profile_bloodpressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan_akun/images'),
        ),
    ]
