# Generated by Django 4.1 on 2022-10-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_review_review_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='review',
        ),
    ]
