# Generated by Django 4.1 on 2022-10-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dokter',
        ),
        migrations.DeleteModel(
            name='Pasien',
        ),
    ]
